# These are supported funding model platforms

github: ['kennedy-ex', 'riz-ex', 'aryazakaria01', 'FeriEXP']
community_bridge: kennedy-project
custom: ['https://t.me/do_dil_ek_jaan143', 'https://t.me/RONNY_KI_DUNIYA']
